### PR TITLE
Update ContentView.swift

### PR DESCRIPTION
**Pull request by tleatminnect**
I want to test. Help me with test.

## Summary by CodeRabbit

- **Style**
	- Updated the greeting text in the UI for a more engaging user experience.

### CODE REVIEW

**Comment by tleatminnect** [comment]
explains this code

**Comment by tleatminnect** [comment]
@coderabbitai review this code

**Review by tleatminnect — COMMENTED** [review]
review this code

**Comment by triledev** [comment]
@coderabbitai explains this code

**Comment by triledev** [comment]
@coderabbitai create unit test

**Comment by triledev** [comment]
give me an summary of the entire codebase

**Pull request merged**
